### ISSUE TITLE
Cannot connect with other nodes

### ISSUE THREAD

**Issue by harleckinz** [Yoshino-s/n8n-nodes-container#1]
Hi! I ran into an error that I'm not able to connect with other nodes.

![Screenshot 2023-08-28 at 11-39-58 n8n - ▶️ Docker List Used Ports](https://github.com/Yoshino-s/n8n-nodes-container/assets/25708009/23f42aff-b964-4794-8bac-4f6ea903ba8d)

n8n version: 1.3.1

Can you help me? :)

**Comment by yoshino-s** [comment]
fixed in 0.1.6

**Comment by yoshino-s** [comment]
a bug was made in 0.1.6 and 0.1.7, please use 0.1.8 now

**Comment by harleckinz** [comment]
Yep. 0.1.7 had the same issue. The 0.1.8 works well! Thanks!
